# Settings for https://probot.github.io/apps/stale/

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1
# Issues with these labels will never be considered stale
exemptLabels:
  - Accessibility
  - Pinned
# Label to use when marking an issue as stale
staleLabel: Icebox
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been inactive for 180 days and labled with `Icebox`.
  It will be closed in 24 hours if there is no further activity.
  Feel free to reopen if you and your team agree it is high priority
  and will be addressed in the next 30 days.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
