name: polaris-react
up:
  - node:
      yarn: true
      version: v8.9.4 # to be kept in sync with .nvmrc and .circleci/config.yml
  - git_hooks:
      pre-commit: pre-commit

commands:
  # People new to the project might be tempted to run some
  # common commands, so let’s have them in here.
  # For a list of Common Commands in Projects, check out:
  # https://github.com/Shopify/dev/wiki/Common-Commands-in-Projects
  build: yarn build
  server: yarn dev
  style: yarn lint
  test: yarn test
  type-check: yarn ts
